name: PyPI Publish

on:
    push:
        tags:
            - "*.*.*"

jobs:
    pypi-publish:
        name: Upload release to PyPI
        runs-on: ubuntu-latest
        permissions:
            id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  cache: pip
                  cache-dependency-path: pyproject.toml
                  python-version: 3.7
            - name: Install load-atoms and dependencies
              run: pip install -e ".[dev]"
            - name: Build
              run: python -m build
            - name: Check
              run: twine check dist/*
            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  password: ${{ secrets.PYPI_API_TOKEN }}
